[package]
name = "didungeon7"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorful = "0.2.2"
miniserde = "0.1.39"
rand = "0.8.5"
rand_chacha = "0.3.1"
